### ISSUE TITLE
Error when trying to test with batch size = 1

### ISSUE THREAD

**Issue by aquariusnk** [cardwing/Codes-for-Lane-Detection#14]
I edit the default batch size in test_lanenet.py and global_config then get a problem like this:
...
Traceback (most recent call last):
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 654, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Index out of range using input dim 3; input has only 3 dims for 'lanenet_loss/inference/encode/strided_slice_37' (op: 'StridedSlice') with input shapes: [36,100,128], [4], [4], [4] and with computed input tensors: input[3] = <1 1 1 1>.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tools/test_lanenet.py", line 138, in <module>
    test_lanenet(args.image_path, args.weights_path, args.use_gpu, img_name, args.batch_size)
  File "tools/test_lanenet.py", line 68, in test_lanenet
    binary_seg_ret, instance_seg_ret = net.inference(input_tensor=input_tensor, name='lanenet_loss')
  File "/home/aquarius/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/lanenet_model/lanenet_merge_model.py", line 114, in inference
    inference_ret = self._build_model(input_tensor=input_tensor, name='inference')
  File "/home/aquarius/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/lanenet_model/lanenet_merge_model.py", line 49, in _build_model
    name='encode')
  File "/home/aquarius/Codes-for-Lane-Detection/SCNN-Tensorflow/lane-detection-model/encoder_decoder_model/vgg_encoder.py", line 240, in encode
    feature_list_old.append(tf.expand_dims(processed_feature[:, :, cnt, :], axis=2))
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 509, in _SliceHelper
    name=name)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 677, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3744, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1861, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/aquarius/anaconda3/envs/tensorflow_gpu/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Index out of range using input dim 3; input has only 3 dims for 'lanenet_loss/inference/encode/strided_slice_37' (op: 'StridedSlice') with input shapes: [36,100,128], [4], [4], [4] and with computed input tensors: input[3] = <1 1 1 1>.
--------------------------------------------------------

If I use batch size = 8, I encounter this problem:
2018-12-06 16:02:34.287785: E tensorflow/stream_executor/cuda/cuda_dnn.cc:371] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-12-06 16:02:34.287807: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-12-06 16:02:34.287813: F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms) 
Aborted (core dumped)
-----------------

I am using Ubuntu 16.04 with conda python 3.5 to work on your code.

**Comment by cardwing** [comment]
@aquariusnk , please refer to [this issue](https://github.com/cardwing/Codes-for-Lane-Detection/issues/10). The batch_size used in training and testing is the same since I specify the batch_size channel in the training process.

**Comment by cardwing** [comment]
Changing batch size to 8 in the testing phase of the pre-trained model should fix this error.

**Comment by aquariusnk** [comment]
Thank you for your fast reply. However, when I try to test the pre-trained model with batch size = 8, I got error with CUDNN as I mentioned above:
2018-12-06 16:02:34.287785: E tensorflow/stream_executor/cuda/cuda_dnn.cc:371] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-12-06 16:02:34.287807: E tensorflow/stream_executor/cuda/cuda_dnn.cc:338] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-12-06 16:02:34.287813: F tensorflow/core/kernels/conv_ops.cc:672] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms)
Aborted (core dumped)
-------------
So could you help me to fix this problem or anyplace where I can get more information about it?

**Comment by cardwing** [comment]
@aquariusnk , please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/6698). I guess it is caused by the allocation of GPU memory. Check if that issue can help you fix the error.

**Comment by aquariusnk** [comment]
I have fixed the problem by updating the tensorflow version to 1.10.0. I think the problem was caused by lacking the support of tensorflow version 1.3.5.
Thank you for helping me in this problem.

**Comment by cardwing** [comment]
^_^
